Repository stolostron/governance-policy-addon-controller, pull requests merged in 2024-08, with the labels that each got.

#636 Refresh the build due to Prow failures
  README.md
Labels: approved, lgtm, dco-signoff: yes

#637 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/governance-policy-addon-controller-acm-210-pull-request.yaml
  .tekton/governance-policy-addon-controller-acm-210-push.yaml
Labels: approved, lgtm, dco-signoff: yes, ok-to-test

#638 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/governance-policy-addon-controller-acm-211-pull-request.yaml
  .tekton/governance-policy-addon-controller-acm-211-push.yaml
Labels: approved, lgtm, dco-signoff: yes, ok-to-test

#643 Re-Sync from open-cluster-management-io/governance-policy-addon-controller: #173
  pkg/addon/policyframework/agent_addon.go
Labels: approved, dco-signoff: yes
